name: tests

on:
  push:
  pull_request:

jobs:
  test:
    name: python-tests
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Read versioning files
        id: pyversion
        run: echo "version=$(cat .python-version)" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.pyversion.outputs.version }}
      
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          # Install a specific version of uv.
          version: "0.9.21"

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r requirements.txt
          uv pip install -e .

      - name: Run tests
        run: |
          uv run pytest -m "not slow"
